name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ai_orchestrator
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ai_orchestrator
      REDIS_URL: redis://localhost:6379
      NEXTAUTH_SECRET: testsecret1234567890testsecret
      NEXTAUTH_URL: http://localhost:3000
      OPENAI_API_KEY: test-openai
      SUNO_API_KEY: test-suno
      SUNO_BASE_URL: https://api.suno.ai
      SUNO_USE_MOCK: true
      ENCRYPTION_KEY: 12345678901234567890123456789012
      JWT_SIGNING_KEY: 12345678901234567890123456789012
      FRONTEND_URL: http://localhost:3000
      API_URL: http://localhost:4000
      WORKER_URL: http://localhost:4001
      QUEUE_PREFIX: ai
      AUTH_DISABLED: true
      TEST_BYPASS_AUTH: true
      S3_ENDPOINT: https://s3.example.com
      S3_ACCESS_KEY_ID: access-key
      S3_SECRET_ACCESS_KEY: secret
      S3_BUCKET: test-bucket
      STRIPE_SECRET_KEY: sk_test
      STRIPE_WEBHOOK_SECRET: wh_test
      TOSS_SECRET_KEY: toss_test
      TOSS_CLIENT_KEY: toss_client
      TOSS_WEBHOOK_SECRET: toss_webhook
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm generate
      - run: pnpm lint
      - run: pnpm test:unit
      - run: pnpm exec playwright install --with-deps
      - run: pnpm test:e2e
